name: build-publish

on:
  push:
    branches:
      - release
    paths-ignore:
      - '.idea/**'
      - 'notes/**'
      - 'README.md'
      - '**/README.md'

jobs:
  main:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1 # needed for twine
      with:
        python-version: '3.8.12'
    - name: Build, test and publish to PyPI
      run: |
        script/do-build-publish.sh $(which python) ${{ secrets.pypi_password }} pypi
